background {
    monitor =
    path = screenshot
    blur_passes = 4
    blur_size = 10
    color = rgba(15, 15, 20, 0.75) # Adds dark opacity over the screenshot
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font 10
    placeholder_text = <span font_style="normal">Input Password</span>
    font_color = rgb(200, 200, 200)
    inner_color = rgba(20, 20, 30, 0.6) # Darker input field background
    outer_color = rgba(255, 255, 255, 0.2)
}
