#################
### AUTOSTART ###
#################

$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = awww-daemon
exec-once = waybar
exec-once = swaync
