#################
### AUTOSTART ###
#################

$terminal = kitty
$fileManager = kitty -e yazi
$menu = rofi -show drun

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = awww-daemon
exec-once = waybar
exec-once = swaync

# Clipboard history daemons
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-clip-persist --clipboard regular
